### ISSUE TITLE
Error MSF RPC not connected

### ISSUE THREAD

**Issue by MiriDevAndro** [cSploit/android#1014]
DEVICE:GM 5

OS version:7.1.1

**cSploit version:** 1.6.6-rc.2

**busybox** *(installed or not):* installed 

**Rooted with supersu?** magisk

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

08-15 18:26:17.553 16340 16340 D CSPLOIT[core.System.setCurrentPlugin]: Setting current plugin : Sessions
08-15 18:26:17.558  2469 14626 I ActivityManager: START u0 {cmp=org.csploit.android/.plugins.Sessions} from uid 10118 on display 0
08-15 18:26:17.603 16340 16340 W csploit.android: type=1400 audit(0.0:69109): avc: denied { read } for name="xposed" dev="mmcblk0p31" ino=24531 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
08-15 18:26:17.603 16340 16340 W csploit.android: type=1400 audit(0.0:69110): avc: denied { read } for name="xposed" dev="mmcblk0p31" ino=24531 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
08-15 18:26:17.845  2469  2551 I ActivityManager: Displayed org.csploit.android/.plugins.Sessions: +265ms
08-15 18:26:19.562  2469  2469 W WindowManager: Attempted to remove non-existing token: android.os.Binder@2adde00
08-15 18:26:23.466 13953 13982 I Finsky  : [1964] ian.run(3): Stats for Executor: BlockingExecutor ibu@ad6db87[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 17]
08-15 18:26:23.467 13953 13982 I Finsky  : [1964] ian.run(3): Stats for Executor: LightweightExecutor ibu@5c8cab4[Running, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 67]
08-15 18:26:23.800 13953 13982 I Finsky  : [1964] ian.run(3): Stats for Executor: bgExecutor ibu@f7956dd[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 50]
08-15 18:26:56.935   405   405 I VM_BMS  : power_supply_update: ocv_uv=4042722 ibatt=-293584 soc=75 seq_num=410
08-15 18:26:59.884  2469  2546 E BatteryStatsService: no controller energy info supplied
08-15 18:26:59.884  2469  2546 E BatteryStatsService: no controller energy info supplied
08-15 18:26:59.892  2469  2546 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
08-15 18:27:01.840 16340 16340 D CSPLOIT[core.System.setCurrentPlugin]: Setting current plugin : Sessions
08-15 18:27:01.845  2469  6671 I ActivityManager: START u0 {cmp=org.csploit.android/.plugins.Sessions} from uid 10118 on display 0
08-15 18:27:01.883 16340 16340 W csploit.android: type=1400 audit(0.0:69111): avc: denied { read } for name="xposed" dev="mmcblk0p31" ino=24531 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
08-15 18:27:01.883 16340 16340 W csploit.android: type=1400 audit(0.0:69112): avc: denied { read } for name="xposed" dev="mmcblk0p31" ino=24531 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
08-15 18:27:02.070  2469  2551 I ActivityManager: Displayed org.csploit.android/.plugins.Sessions: +201ms
08-15 18:27:03.856  2469  2469 W WindowManager: Attempted to remove non-existing token: android.os.Binder@11cf6c7
08-15 18:27:15.272 16340 16340 D CSPLOIT[core.System.setCurrentPlugin]: Setting current plugin : Sessions
08-15 18:27:15.277  2469  6672 I ActivityManager: START u0 {cmp=org.csploit.android/.plugins.Sessions} from uid 10118 on display 0
08-15 18:27:15.313 16340 16340 W csploit.android: type=1400 audit(0.0:69113): avc: denied { read } for name="xposed" dev="mmcblk0p31" ino=24531 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
08-15 18:27:15.313 16340 16340 W csploit.android: type=1400 audit(0.0:69114): avc: denied { read } for name="xposed" dev="mmcblk0p31" ino=24531 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
08-15 18:27:15.509  2469  2551 I ActivityManager: Displayed org.csploit.android/.plugins.Sessions: +211ms
08-15 18:27:17.281  2469  2469 W WindowManager: Attempted to remove non-existing token: android.os.Binder@3084eaf
08-15 18:27:17.304   291   427 E BufferQueueProducer: [Toast] cancelBuffer: BufferQueue has been abandoned
08-15 18:27:17.311  2469  3884 W WindowManager: Failed looking up window
08-15 18:27:17.311  2469  3884 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@31526cb does not exist
08-15 18:27:17.311  2469  3884 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9428)
08-15 18:27:17.311  2469  3884 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9419)
08-15 18:27:17.311  2469  3884 W WindowManager: 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2394)
08-15 18:27:17.311  2469  3884 W WindowManager: 	at com.android.server.wm.Session.remove(Session.java:202)
08-15 18:27:17.311  2469  3884 W WindowManager: 	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:242)
08-15 18:27:17.311  2469  3884 W WindowManager: 	at com.android.server.wm.Session.onTransact(Session.java:145)
08-15 18:27:17.311  2469  3884 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:565)

**Daemon specific questions**

Go version: 

OS: 7.1.1

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
*Remember to search for issues alike before creating new one!*

Error MSF RPC not connected

**Comment by ghost** [comment]
cSploit isn't in development currently
