### ISSUE TITLE
cant install msf 

### ISSUE THREAD

**Issue by BEOWULF74** [cSploit/android#160]
Error log
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.core.ChildManager.async(ChildManager.java:83)
	at org.csploit.android.tools.Tool.async(Tool.java:55)
	at org.csploit.android.tools.Raw.async(Raw.java:60)
	at org.csploit.android.core.UpdateService.extract(UpdateService.java:1052)
	at org.csploit.android.core.UpdateService.onHandleIntent(UpdateService.java:1427)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by BEOWULF74** [comment]
What the matters. With you tux-mind talk with us man >_< !!

**Comment by sorano** [comment]
Duplicate of #205
