### ISSUE TITLE
	at org.csploit.android.MainActivity.createUpdateLayout(MainActivity.java:142)

### ISSUE THREAD

**Issue by gainan** [cSploit/android#399]
Reported with stable version 1.6.0, and present in all branches.

>java.lang.NullPointerException: **Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference**
at org.csploit.android.MainActivity.createUpdateLayout(MainActivity.java:142)
at org.csploit.android.MainActivity.createLayout(MainActivity.java:237)
at org.csploit.android.MainActivity.access$400(MainActivity.java:100)
at org.csploit.android.MainActivity$3.run(MainActivity.java:289)
at android.app.Activity.runOnUiThread(Activity.java:5575)
at org.csploit.android.MainActivity.onCoreUpdated(MainActivity.java:285)
at org.csploit.android.MainActivity.access$900(MainActivity.java:100)
at org.csploit.android.MainActivity$UpdateReceiver.onUpdateDone(MainActivity.java:1038)
at org.csploit.android.MainActivity$UpdateReceiver.onReceive(MainActivity.java:1092)

The problem is that the string is not initialized:
```
private String UPDATE_MESSAGE;
```

it seems to be there a race condition where the string is accessed before being initialized.

**Comment by tux-mind** [comment]
will be fixed once #245 get merged, thanks for the report :blush: 

we may should think about an auto-reporter from ACRA... or switch to another bug report framework.

**Comment by tux-mind** [comment]
fixed in #245
