### ISSUE TITLE
cannot load native libraries on android 2.3.x

### ISSUE THREAD

**Issue by gainan** [cSploit/android#400]
The following error has been reported with 1.6.0 version 2, with android 2.3.x (7 reports):
>java.lang.ExceptionInInitializerError
at org.csploit.android.core.ChildManager.async(ChildManager.java:86)
at org.csploit.android.tools.Tool.async(Tool.java:59)
at org.csploit.android.tools.NetworkRadar.start(NetworkRadar.java:61)
at org.csploit.android.services.NetworkRadar.start(NetworkRadar.java:40)
at org.csploit.android.MainActivity$7.run(MainActivity.java:564)
at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.UnsatisfiedLinkError: unknown failure
at java.lang.Runtime.loadLibrary(Runtime.java:434)
at java.lang.System.loadLibrary(System.java:554)
at org.csploit.android.core.Client.<clinit>(Client.java:10)

**Comment by tux-mind** [comment]
```
java.lang.NoSuchMethodError: getByAddress
 at java.lang.Runtime.nativeLoad(Native Method)
 at java.lang.Runtime.loadLibrary(Runtime.java:432)
 at java.lang.System.loadLibrary(System.java:554)
 at org.csploit.android.core.Client.<clinit>(Client.java:10)
 at org.csploit.android.core.System.shutdownCoreDaemon(System.java:308)
 at org.csploit.android.services.UpdateService.onHandleIntent(UpdateService.java:948)
 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 android.os.Looper.loop(Looper.java:130)
 at android.os.HandlerThread.run(HandlerThread.java:60)
 JNI_OnLoad: cannot init cache
 JNI_OnLoad returned bad version (-1) in /mnt/asec/org.csploit.android-1/lib/libcSploitClient.so 0x40515050
```

**Comment by tux-mind** [comment]
fixed in cSploit/android.native@ec1fa6a
