### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1

### ISSUE THREAD

**Issue by gainan** [cSploit/android#437]
Version 1.6.2, core tools 1.0.8, after close the app:

>10-15 16:06:58.170  18271-18271/? E/ACRA﹕ ACRA caught a IndexOutOfBoundsException for org.csploit.android
    java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at org.csploit.android.MainActivity$TargetAdapter$1.run(MainActivity.java:953)
            at android.os.Handler.handleCallback(Handler.java:733)

**Comment by gainan** [comment]
after update the core tools, having the hosts list filled up, and the scrollbar on the middle of the list:
>10-15 16:18:49.824  21206-26409/org.csploit.android E/ACRA﹕ org.csploit.android fatal error : Invalid index 43, size is 4
    java.lang.IndexOutOfBoundsException: Invalid index 43, size is 4
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at org.csploit.android.MainActivity$TargetAdapter$1.run(MainActivity.java:953)
