### ISSUE TITLE
error downloading update msf

### ISSUE THREAD

**Issue by evertking** [cSploit/android#506]
I did a fresh install of the new nightly and got all the updates except MSF

**Comment by BEOWULF74** [comment]
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by BEOWULF74** [comment]
Version 1.7.0 nightly

**Comment by BEOWULF74** [comment]
And after core installation failure the app doesn't ask me about install ruby or msf I gave u all information I have hope u will fix it guys love u all :)

**Comment by fat-tire** [comment]
Beowulf-- can you clear data from the app and start again and see if there is an error in the log like described in #503 ?

Thanks!

**Comment by tux-mind** [comment]
@BEOWULF74 please post a logcat, we cannot understand the problem otherwise.

thank you for the report :blush:
