### ISSUE TITLE
Can't install ruby, MSF, rubyGem properly, can't start

### ISSUE THREAD

**Issue by jackz314** [cSploit/android#627]
I downloaded the apk, but it only reminds me to install the core, while I don't have other needed files, please tlee me how to install those files so that I can start the software properly :)

These are logs

org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by LikeZer0** [comment]
I'm no expert, but have you checked if SuperSU is blocking root requests from cSploit?

**Comment by s0mew0n** [comment]
Do you have busybox installed? I did this once, it would have a pop up saying the something went wrong with the download.

**Comment by venus342** [comment]
Download latest busybox (Stericson works fine) from google play, and get latest SuperSU.
If you use Kingroot or Kinguser consider switching to SuperSU

**Comment by IwraStudios** [comment]
Old issue; clone of https://github.com/cSploit/android/issues/668 and resolved
