### ISSUE TITLE
when update core.tar.xz, give a tip "update cancel", below are logs:

### ISSUE THREAD

**Issue by CharellKing** [cSploit/android#668]
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

i found that when firstly opened csploit, it always asked root access, but now no more.

**Comment by CharellKing** [comment]
// consume the archive
while (mRunning && (entry = is.getNextEntry()) != null) {
        if(!mCurrentTask.skipRoot) continue;

        String name = entry.getName();



'mCurrentTask.skipRoot'  never to be true. so it's a dead cycle.  why "is.getNextEntry()" is not to be null

**Comment by CharellKing** [comment]
Okey, i resolved it, i must install busybox in "/system/xbin"
