### ISSUE TITLE
replace image from local image error

### ISSUE THREAD

**Issue by Doums** [cSploit/android#704]
Hi,

First thanks for your work !

The issue I found : 
When I try "replace image" and I choose "local image" I got this error msg "Could not determine file path"

If you need more information for fix this tell me !

**Comment by IwraStudios** [comment]
can you upload a logcat and please read https://github.com/cSploit/android/wiki/How-to-open-an-issue

**Comment by Doums** [comment]
Here :

device One Plus 3
ROM : OxygenOS 3.2.1
cSploit version : version 1.6.6-rc.2
network : my home router (Orange Livebox)
Iam not using  Xposed
App start ups ok.
Network hosts list appear and are clickable.
Select the MITM module works.
Select the Session hijacker module works.

[c.txt](https://github.com/cSploit/android/files/382327/c.txt)

**Comment by IwraStudios** [comment]
Errors:

> E/CSPLOIT[core.System.errorLogging] ]
cannot start commands

[ 07-25 21:15:02.487 30321:30337 E/CSPLOIT[core.System.errorLogging] ]
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

> W/CSPLOIT[services.MsfRpcdService.connect] ]
java.net.ConnectException: failed to connect to /127.0.0.1 (port 55553): connect failed: ECONNREFUSED (Connection refused)

ignore second error for now, since it has nothing to do with MITM like replacing image
