### ISSUE TITLE
Error after start

### ISSUE THREAD

**Issue by gitty8** [cSploit/android#712]
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
    at org.csploit.android.tools.Tool.async(Tool.java:48)
    at org.csploit.android.tools.NMap.synScan(NMap.java:142)
    at org.csploit.android.tools.NMap.synScan(NMap.java:146)
    at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
    at org.csploit.android.tools.Tool.async(Tool.java:48)
    at org.csploit.android.tools.NMap.synScan(NMap.java:142)
    at org.csploit.android.tools.NMap.synScan(NMap.java:146)
    at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
    at org.csploit.android.tools.Tool.async(Tool.java:48)
    at org.csploit.android.tools.NMap.synScan(NMap.java:142)
    at org.csploit.android.tools.NMap.synScan(NMap.java:146)
    at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
    at org.csploit.android.tools.Tool.async(Tool.java:48)
    at org.csploit.android.tools.NMap.synScan(NMap.java:142)
    at org.csploit.android.tools.NMap.synScan(NMap.java:146)
    at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

**Comment by Silur** [comment]
Can you please provide the output of the `/data/data/org.csploit.android/files/csploitd.log` file too?
