### ISSUE TITLE
Fail to download core update due to a weird SSL validation error

### ISSUE THREAD

**Issue by zyk** [cSploit/android#747]
### The problem
First time start: core update popup (v1.0.11) shows up.
Click on it and receive 'An error occured while downloading the update.'

### Going a bit deeper
Logcat outputs a SSL certificate trust issue. 
Checking a network log I see two connections to github:
1. Getting update info from api.github.com (192.30.253.11**2**)
2. Download: another github server (192.30.253.11**6**, [no PTR found](https://mxtoolbox.com/SuperTool.aspx?action=ptr%3a192.30.253.116&run=toolpage))
Crossreferencing the first response and logcat, the second url *should* be [this](https://github.com/cSploit/android.native/releases/download/v1.0.11/core-v1.0.11.android16.armeabi-v7a.tar.xz) right?

Looking up the URL with curl on desktop ([curl_log.txt](https://github.com/cSploit/android/files/486716/curl.txt)) shows a connection to .112 server...
***While the app connects to .116 ...***

### Versions and stuff
- cSploit version: 1.6.5 (f-droid)
- Device model: Samsung S4 Mini (GT-I19195)
- Android: 4.4.4
- ROM: Pacman ROM KK Release dev [forum page](http://forum.xda-developers.com/galaxy-s4-mini/development/rom-pac-rom-kk-rc-3-t2944807)
- Busybox 1.24.2-meefik (f-droid)
- supersu

*network*

- Both devices are on same network and use the same DNS.
- Same problem when using a LTE connection.
- If I ping github.com in a terminal on the phone: **.112**
- No problem downloading the package using firefox.

### Logcat:

*Starting the app*
```
D/CSPLOIT[services.UpdateChecker.run]( 7768): Service started.
D/CSPLOIT[net.RemoteReader.run]( 7768): RemoteReader[api.github.com] started
I/CSPLOIT[net.RemoteReader.run]( 7768): fetching 'https://api.github.com/repos/cSploit/android/releases'
D/CSPLOIT[core.System.readFirstLine]( 7768): /data/data/org.csploit.android/files/msf/VERSION: open failed: ENOENT (No such file or directory)
D/CSPLOIT[core.System.readFirstLine]( 7768): /data/data/org.csploit.android/files/msf/VERSION: open failed: ENOENT (No such file or directory)
D/CSPLOIT[services.UpdateChecker.getApkUpdate]( 7768): localVersion   = 1.6.5
D/CSPLOIT[services.UpdateChecker.getApkUpdate]( 7768): remoteVersion  = 1.6.5
D/CSPLOIT[core.System.readFirstLine]( 7768): /data/data/org.csploit.android/files/VERSION: open failed: ENOENT (No such file or directory)
I/CSPLOIT[net.RemoteReader.run]( 7768): fetching 'https://api.github.com/repos/cSploit/android.native/releases'
W/CSPLOIT[services.UpdateChecker.getCoreUpdate]( 7768): unsupported platform ( android19.armeabi-v7a )
D/CSPLOIT[services.UpdateChecker.getCoreUpdate]( 7768): trying with 'android16.armeabi-v7a'
D/CSPLOIT[services.UpdateChecker.getCoreUpdate]( 7768): localVersion   = null
D/CSPLOIT[services.UpdateChecker.getCoreUpdate]( 7768): remoteVersion  = 1.0.11
D/CSPLOIT[services.UpdateChecker.run]( 7768): Service stopped.
```
*Clicking OK*

```
E/CSPLOIT[core.System.errorLogging]( 7768): java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/CSPLOIT[core.System.errorLogging]( 7768): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certificationpath not found.
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.Connection.connect(Connection.java:107)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
E/CSPLOIT[core.System.errorLogging]( 7768):     at org.csploit.android.services.UpdateService.downloadFile(UpdateService.java:564)
E/CSPLOIT[core.System.errorLogging]( 7768):     at org.csploit.android.services.UpdateService.onHandleIntent(UpdateService.java:945)
E/CSPLOIT[core.System.errorLogging]( 7768):     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/CSPLOIT[core.System.errorLogging]( 7768):     at android.os.Handler.dispatchMessage(Handler.java:102)
E/CSPLOIT[core.System.errorLogging]( 7768):     at android.os.Looper.loop(Looper.java:136)
E/CSPLOIT[core.System.errorLogging]( 7768):     at android.os.HandlerThread.run(HandlerThread.java:61)
E/CSPLOIT[core.System.errorLogging]( 7768): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor fo certification path not found.
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/CSPLOIT[core.System.errorLogging]( 7768):     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
E/CSPLOIT[core.System.errorLogging]( 7768):     ... 15 more
E/CSPLOIT[core.System.errorLogging]( 7768): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/CSPLOIT[core.System.errorLogging]( 7768):     ... 20 more
D/CSPLOIT[services.UpdateService.finishNotification]( 7768): deleting notifications
```

Might compile cSploit and debug this later in the week if time permits, because this is interesting :)

**Comment by IwraStudios** [comment]
first of I really like the time you put in this to figure it out by yourself and supplying a of info

the thing is f-droid's cSploit app hasn't been updated in a while we have [1.6.6 RC2](https://github.com/cSploit/android/releases) now even though its technically a pre-release

**Comment by zyk** [comment]
Thanks man!
OK, I will use the google play version instead, thanks!

**Comment by IwraStudios** [comment]
we aren't allowed on the google play store (i think) as it is a "pen-testing/hacking/malicious" app

**Comment by zyk** [comment]
Yeah I saw that. Tried the 1.6.6 RC2 apk but had the same issue as the f-droid version (haven't checked logcat though)

I will try to compile and debug it in the weekend.

**Comment by zyk** [comment]
I've played around a bit now and think I've found the problem.

```
09-24 12:57:18.856 18889-18921/io.jigoku.networktester D/Test #1: https://github.com : code 200
09-24 12:57:19.106 18889-18923/io.jigoku.networktester D/Test #2: https://github.com/cSploi  (download URL): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-24 12:57:18.485 18889-18922/io.jigoku.networktester D/Test #3: https://github-cloud.s3.a.. (redirected URL) : javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

My phone does not trust the Amazon S3 certificate.
So no bugs, just an outdated ROM or android 4.4 does not have all the Digicert CA's.

Well it was fun to debug! Now on to install the certificates missing.

**Comment by IwraStudios** [comment]
i hope it works out
