### ISSUE TITLE
cannot find core for this device!! S3 GT-i900

### ISSUE THREAD

**Issue by One278** [cSploit/android#841]
##DEVICE:
S3 GT-i900

##OS version:
4.3

##cSploit version:
1.6.6 RC2

##busybox (installed or not):
Yes

##Rooted with supersu?
Yes

##Using Xposed or not?
No

#Logs:
csploit-debug-error:

org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

**Comment by One278** [comment]
😒

**Comment by IwraStudios** [comment]
Right sorry,
We don't actually know what causes this problem yet, but as your problem is "not having a core" i would suggest looking at #650
