### ISSUE TITLE
Sometimes when I use mitm, the phone will reboot

### ISSUE THREAD

**Issue by ZhenBab** [cSploit/android#856]
##DEVICE:
NEXUS 6
##OS version:
andoid 6.0.1

##cSploit version:
csploit v1.6.6-rc.2

##busybox (installed or not):

##Rooted with supersu?
v1.25.0-Nethunter

##logcat (filter it!):

**Daemon specific questions**

##Go version:

##OS:

##Using Docker (incase of unofficial build.)

##Actions performed:

#Logs:

##Issue:
*Remember to search for issues alike before creating new one.

**Comment by ZhenBab** [comment]
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
