### ISSUE TITLE
Crashes, freezes, and reboots system when attempting MITM on WiFi

### ISSUE THREAD

**Issue by keeganjk** [cSploit/android#901]
DEVICE: OnePlus 5

OS version: OxygenOS 4.5.12

**cSploit version:** 1.66_rc.2

**busybox** *(installed or not):* Installed

**Rooted with supersu?** Magisk

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238) N/A

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions** N/A

Go version: ???

OS: ???

Using Docker (incase of unofficial build.) ???

Actions performed:
I sometimes use cSploit on WiFi and when I chose the network and select MITM and Kill Connections or Custom Filter, it freezes and reboots after a few seconds. I've installed https://forum.xda-developers.com/android/software-hacking/kali-nethunter-magisk-t3676681/post74014575 and https://build.nethunter.com/nightly/3.20-20170903-2143/kernel-nethunter-oneplus5-oos-nougat-3.20-20170903-2143.zip afterwards. I manually installed cSploit from F-Droid.

Logs:
```
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
at org.csploit.android.tools.Tool.async(Tool.java:48)
at org.csploit.android.tools.NMap.synScan(NMap.java:142)
at org.csploit.android.tools.NMap.synScan(NMap.java:146)
at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
at org.csploit.android.tools.Tool.async(Tool.java:48)
at org.csploit.android.tools.NMap.synScan(NMap.java:142)
at org.csploit.android.tools.NMap.synScan(NMap.java:146)
at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
at org.csploit.android.tools.Tool.async(Tool.java:48)
at org.csploit.android.tools.NMap.synScan(NMap.java:142)
at org.csploit.android.tools.NMap.synScan(NMap.java:146)
at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

```
**Issue:**
*Remember to search for issues alike before creating new one!*
Crashes, freezes, and reboots system when attempting MITM on WiFi

**Comment by keeganjk** [comment]
Here is the a debug file I found:
```
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by pahapoika** [comment]
Hey @keeganjk
Can you try csploit from https://github.com/cSploit/android/releases/download/v1.6.6-rc.2/cSploit-release.apk

Thank you

**Comment by keeganjk** [comment]
@pahapoika arpspoof error

**Comment by keeganjk** [comment]
@pahapoika Still crashes after about 10 seconds when trying to kill connections on public network.

**Comment by keeganjk** [comment]
It doesn't even _kill_ any connections, it just shows the circular animation by Kill Connections.

**Comment by pahapoika** [comment]
@keeganjk can you try it on your own wifi with only few devices. cSploit (or your device) might not be able to arp spoof on big networks. The network might also use static ARP aswell, so that might also prevent the attacks.

**Comment by keeganjk** [comment]
@pahapoika If I wait for it to connect to Metasploit, Kill Connections appears to work on my home network.

How can I get this to work on a larger network? (And not have my device reboot ;))

**Comment by keeganjk** [comment]
@pahapoika I installed BusyBox, not sure if it was already installed, tried [custom filter replacing "a" with "b", pressing OK, replacing "b" with "a", killing connections, un-killing connections ] to my laptop, started trying to browse the internet on my laptop to see if it would work, looked over and saw my phone freeze and reboot...

**Comment by keeganjk** [comment]
@pahapoika Here is the text from the debug file from The session of the crash:
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by keeganjk** [comment]
@pahapoika Is there a way I could send reconnect packets to everyone on the network instead of using ARP to kill connects?

**Comment by pahapoika** [comment]
Hey @keeganjk
You can use mitm to redirect all connections to 127.0.0.1 and it should do the job

**Comment by keeganjk** [comment]
Do you think that could potentially cause a crash/reboot?

**Comment by pahapoika** [comment]
@keeganjk it shouldn't

**Comment by keeganjk** [comment]
@pahapoika Any guesses on what's causing crash on custom filter and kill connections?

**Comment by pahapoika** [comment]
@keeganjk you kinda skipped the issue template we have, so I don't have much information.

**Comment by keeganjk** [comment]
@pahapoika Sorry, I was using an unofficial GitHub client that doesn't bring that up. Will edit now.

**Comment by pahapoika** [comment]
@keeganjk no need.
Just answer these questions.
What's your phone:
What Android version it's running:
csploit version:
BusyBox installed or not:
What app you use for root

**Comment by keeganjk** [comment]
@pahapoika
OnePlus 5
OxygenOS 4.5.12
The cSploit version you told me to dowload (v1.6.6)
BusyBox installed
Magisk

**Comment by keeganjk** [comment]
@pahapoika My device lags really badly when running cSploit. Is this normal?

**Comment by keeganjk** [comment]
@pahapoika Redirection to 127.0.0.1 doesn't kill connections, but it doesn't reboot my phone either. However, it did bring up an HSTS error when trying a web search, but I could go to other URLs.

**Comment by keeganjk** [comment]
@pahapoika Do you think this problem might be fixed in v2.x?

**Comment by HitItAll** [comment]
@keeganjk No, they spent months working on a broken app.

Sorry, I can't help but be a dick

**Comment by keeganjk** [comment]
@HitItAll I know there will be more than just fixing this feature, but if they're making an entire new version, it might fix some... Problems.

**Comment by pahapoika** [comment]
@HitItAll no need to be rude. Not every device can be tested and maybe OnePlus just did OnePlus and broke something cSploit uses.

@keeganjk If 2.0 wont work I'll ask you to provide few logs, but as of now the bug has low priority since 2.0 is important update.
