### ISSUE TITLE
Nightly issues

### ISSUE THREAD

**Issue by kimocoder** [cSploit/android#971]
DEVICE:
Nexus 6P (angler) running NetHunter

OS version:
7.1.1 Original rom with modified NetHunter kernel

**cSploit version:**
Nightly

**busybox** *(installed or not):*
Installed

**Rooted with supersu?**
Yes

**Issues** 
------------------------------------------------------------------------------------------------------------------------------
* Using "MITM -> Session hijacker" crashed phone. phone reboots.

* Using "MITM -> Redirect" actually does the same as "Kill connection". Redirection doesn't work, but instead makes all sites unavailable.

* Using "MITM -> Script injection" also simply doesn't work. phone might also reboot/crash when using this option.

**Comment by kimocoder** [comment]
These 3 functions isn't working.. it was working with the old *stable" release, at least script injection as I remember. Will test more of the functions soon and update the thread.

**Comment by fat-tire** [comment]
what errors are shown in the log?

**Comment by jonniex7** [comment]
any update for this awesome app or abonded?

**Comment by victor141516** [comment]
I have this same issue. Here is the log:
```java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:205)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:451)
	at java.net.ServerSocket.implAccept(ServerSocket.java:547)
	at java.net.ServerSocket.accept(ServerSocket.java:515)
	at org.csploit.android.net.http.server.Server.run(Server.java:121)
	at java.lang.Thread.run(Thread.java:764)
org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
	at org.csploit.android.tools.Tool.async(Tool.java:48)
	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```
