### ISSUE TITLE
Core Problems

### ISSUE THREAD

**Issue by LorVC** [cSploit/android#991]
DEVICE:LG E400

OS version:4.0.1(cynogenmod) and 2.3.6 (stock lg ux)

**cSploit version:** all version tryed

**busybox** *(installed or not):*yes

**Rooted with supersu?**yes

**logcat** *(filter it!):*
[How-to guide](https://forum.xda-developers.com/showthread.php?t=1726238)

------------------------------------------------------------------------------------------------------------------------------

**Daemon specific questions**

Go version:

OS:

Using Docker (incase of unofficial build.)

Actions performed:

Logs:
------------------------------------------------------------------------------------------------------------------------------

**Issue:**
Cannot start csploit core install,from months ago i was able to download the core,now i can't.Also csploit doesn't call for su permission.The app load but doesnt download anything,i have already downgraded OS and tryed old version of Csploit(with the same problem).I have downloaded manually the core,but i don't know where put those files.Also i have unistalled Xposed

**Comment by LorVC** [comment]
The strange things is that Dsploit works normally ?.?

**Comment by LorVC** [comment]
12-24 13:33:30.849 I/ActivityManager(238): Force stopping package org.csploit.android uid=10030
12-24 13:33:30.849 I/ActivityManager(238): Killing proc 1861:org.csploit.android/10030: force stop
12-24 13:33:30.849 I/ActivityManager(238):   Force finishing activity ActivityRecord{410d0158 org.csploit.android/.MainActivity}
12-24 13:33:30.849 W/ActivityManager(238): Duplicate finish request for ActivityRecord{410d0158 org.csploit.android/.MainActivity}
12-24 13:33:31.029 I/WindowManager(238): WIN DEATH: Window{4106aba0 org.csploit.android/org.csploit.android.MainActivity paused=false}
12-24 13:33:31.489 W/ActivityManager(238): Activity destroy timeout for ActivityRecord{410d0158 org.csploit.android/.MainActivity}
12-24 13:35:12.959 I/ActivityManager(238): START {flg=0x10000000 cmp=org.csploit.android/.MainActivity} from pid 2159
12-24 13:35:13.049 I/ActivityManager(238): Start proc org.csploit.android for activity org.csploit.android/.MainActivity: pid=2180 uid=10030 gids={3003, 1015, 1007}
12-24 13:40:28.969 I/ActivityManager(238): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.csploit.android/.MainActivity} from pid 419
12-24 13:40:36.879 I/ActivityManager(238): Killing 2180:org.csploit.android/10030: remove task
12-24 13:40:36.959 I/WindowManager(238): WIN DEATH: Window{40e95358 org.csploit.android/org.csploit.android.MainActivity paused=true}
12-24 13:40:36.969 I/ActivityManager(238): Process org.csploit.android (pid 2180) has died.
12-24 13:40:46.879 W/ActivityManager(238): Activity destroy timeout for ActivityRecord{40dec590 org.csploit.android/.MainActivity}
12-24 13:41:19.379 I/ActivityManager(238): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.csploit.android/.MainActivity} from pid 419
12-24 13:41:19.449 I/ActivityManager(238): Start proc org.csploit.android for activity org.csploit.android/.MainActivity: pid=2543 uid=10030 gids={3003, 1015, 1007}
12-24 13:41:19.989 D/ACRA    (2543): ACRA is enabled for org.csploit.android, initializing...
12-24 13:41:20.049 D/ACRA    (2543): Looking for error files in /data/data/org.csploit.android/files
12-24 13:41:20.059 D/ACRA    (2543): Looking for error files in /data/data/org.csploit.android/files
12-24 13:41:20.069 D/CSPLOIT[core.System.init](2543): initializing System...
12-24 13:41:20.239 D/CSPLOIT[tools.NMap.synScan](2543): synScan - -sS -P0 --privileged --send-ip --system-dns -vvv 192.168.1.254
12-24 13:41:20.239 W/CSPLOIT[tools.Tool.async](2543): nmap: disabled
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): cannot start commands
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at org.csploit.android.tools.Tool.async(Tool.java:48)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at java.lang.Thread.run(Thread.java:856)
12-24 13:41:20.249 D/CSPLOIT[tools.NMap.synScan](2543): synScan - -sS -P0 --privileged --send-ip --system-dns -vvv 192.168.1.174
12-24 13:41:20.249 W/CSPLOIT[tools.Tool.async](2543): nmap: disabled
12-24 13:41:20.499 D/CSPLOIT[tools.NMap.synScan](2543): synScan - -sS -P0 --privileged --send-ip --system-dns -vvv 192.168.1.254
12-24 13:41:20.499 W/CSPLOIT[tools.Tool.async](2543): nmap: disabled
12-24 13:41:20.499 D/CSPLOIT[tools.NMap.synScan](2543): synScan - -sS -P0 --privileged --send-ip --system-dns -vvv 192.168.1.174
12-24 13:41:20.499 W/CSPLOIT[tools.Tool.async](2543): nmap: disabled
12-24 13:41:20.509 D/CSPLOIT[services.UpdateChecker.run](2543): Service started.
12-24 13:41:20.529 D/CSPLOIT[net.RemoteReader.run](2543): RemoteReader[api.github.com] started
12-24 13:41:20.529 I/CSPLOIT[net.RemoteReader.run](2543): fetching 'https://api.github.com/repos/cSploit/android/releases'
12-24 13:41:20.669 D/CSPLOIT[core.System.readFirstLine](2543): /data/data/org.csploit.android/files/msf/VERSION: open failed: ENOENT (No such file or directory)
12-24 13:41:20.729 D/CSPLOIT[core.System.readFirstLine](2543): /data/data/org.csploit.android/files/msf/VERSION: open failed: ENOENT (No such file or directory)
12-24 13:41:20.819 I/ActivityManager(238): Displayed org.csploit.android/.MainActivity: +1s407ms

**Comment by LorVC** [comment]
12-24 13:33:30.849 I/ActivityManager(238): Force stopping package org.csploit.android uid=10030
12-24 13:33:30.849 I/ActivityManager(238): Killing proc 1861:org.csploit.android/10030: force stop
12-24 13:33:30.849 I/ActivityManager(238):   Force finishing activity ActivityRecord{410d0158 org.csploit.android/.MainActivity}
12-24 13:33:30.849 W/ActivityManager(238): Duplicate finish request for ActivityRecord{410d0158 org.csploit.android/.MainActivity}
12-24 13:33:31.029 I/WindowManager(238): WIN DEATH: Window{4106aba0 org.csploit.android/org.csploit.android.MainActivity paused=false}
12-24 13:33:31.489 W/ActivityManager(238): Activity destroy timeout for ActivityRecord{410d0158 org.csploit.android/.MainActivity}
12-24 13:35:12.959 I/ActivityManager(238): START {flg=0x10000000 cmp=org.csploit.android/.MainActivity} from pid 2159
12-24 13:35:13.049 I/ActivityManager(238): Start proc org.csploit.android for activity org.csploit.android/.MainActivity: pid=2180 uid=10030 gids={3003, 1015, 1007}
12-24 13:40:28.969 I/ActivityManager(238): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.csploit.android/.MainActivity} from pid 419
12-24 13:40:36.879 I/ActivityManager(238): Killing 2180:org.csploit.android/10030: remove task
12-24 13:40:36.959 I/WindowManager(238): WIN DEATH: Window{40e95358 org.csploit.android/org.csploit.android.MainActivity paused=true}
12-24 13:40:36.969 I/ActivityManager(238): Process org.csploit.android (pid 2180) has died.
12-24 13:40:46.879 W/ActivityManager(238): Activity destroy timeout for ActivityRecord{40dec590 org.csploit.android/.MainActivity}
12-24 13:41:19.379 I/ActivityManager(238): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.csploit.android/.MainActivity} from pid 419
12-24 13:41:19.449 I/ActivityManager(238): Start proc org.csploit.android for activity org.csploit.android/.MainActivity: pid=2543 uid=10030 gids={3003, 1015, 1007}
12-24 13:41:19.989 D/ACRA    (2543): ACRA is enabled for org.csploit.android, initializing...
12-24 13:41:20.049 D/ACRA    (2543): Looking for error files in /data/data/org.csploit.android/files
12-24 13:41:20.059 D/ACRA    (2543): Looking for error files in /data/data/org.csploit.android/files
12-24 13:41:20.069 D/CSPLOIT[core.System.init](2543): initializing System...
12-24 13:41:20.239 D/CSPLOIT[tools.NMap.synScan](2543): synScan - -sS -P0 --privileged --send-ip --system-dns -vvv 192.168.1.254
12-24 13:41:20.239 W/CSPLOIT[tools.Tool.async](2543): nmap: disabled
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): cannot start commands
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): org.csploit.android.core.ChildManager$ChildNotStartedException: cannot start commands
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at org.csploit.android.tools.Tool.async(Tool.java:48)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at org.csploit.android.tools.NMap.synScan(NMap.java:142)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at org.csploit.android.tools.NMap.synScan(NMap.java:146)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at org.csploit.android.services.NetworkRadar$2.run(NetworkRadar.java:90)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
12-24 13:41:20.249 E/CSPLOIT[core.System.errorLogging](2543): 	at java.lang.Thread.run(Thread.java:856)
12-24 13:41:20.249 D/CSPLOIT[tools.NMap.synScan](2543): synScan - -sS -P0 --privileged --send-ip --system-dns -vvv 192.168.1.174
12-24 13:41:20.249 W/CSPLOIT[tools.Tool.async](2543): nmap: disabled
12-24 13:41:20.499 D/CSPLOIT[tools.NMap.synScan](2543): synScan - -sS -P0 --privileged --send-ip --system-dns -vvv 192.168.1.254
12-24 13:41:20.499 W/CSPLOIT[tools.Tool.async](2543): nmap: disabled
12-24 13:41:20.499 D/CSPLOIT[tools.NMap.synScan](2543): synScan - -sS -P0 --privileged --send-ip --system-dns -vvv 192.168.1.174
12-24 13:41:20.499 W/CSPLOIT[tools.Tool.async](2543): nmap: disabled
12-24 13:41:20.509 D/CSPLOIT[services.UpdateChecker.run](2543): Service started.
12-24 13:41:20.529 D/CSPLOIT[net.RemoteReader.run](2543): RemoteReader[api.github.com] started
12-24 13:41:20.529 I/CSPLOIT[net.RemoteReader.run](2543): fetching 'https://api.github.com/repos/cSploit/android/releases'
12-24 13:41:20.669 D/CSPLOIT[core.System.readFirstLine](2543): /data/data/org.csploit.android/files/msf/VERSION: open failed: ENOENT (No such file or directory)
12-24 13:41:20.729 D/CSPLOIT[core.System.readFirstLine](2543): /data/data/org.csploit.android/files/msf/VERSION: open failed: ENOENT (No such file or directory)
12-24 13:41:20.819 I/ActivityManager(238): Displayed org.csploit.android/.MainActivity: +1s407ms
